import type { Metadata } from "next";
import { Rubik, Monoton } from "next/font/google";
import "./globals.css";

const monoton = Monoton({
  display: 'swap',
  preload: true,
  subsets: ['latin'],
  variable: '--font-monoton',
  weight: '400'
})

const rubik = Rubik({
  display: 'swap',
  preload: true,
  subsets: ['latin'],
  variable: '--font-rubik',
  weight: ['400', '500', '600']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${monoton.variable} dark scroll
        antialiased items-center justify-center flex 
        `}
      >
        {children}
      </body>
    </html>
  );
}
